export const routeTitles: { [key: string]: string } = {
  "/profile": "Profile",
  "/dashboard": "Dashboard",
  "/campaigns": "Campaigns",
  "/role-management": "Role Management",
  "/user-management": "User Management",
  "/groups-members": "Groups & Members",
  "/email-templates": "Email Templates",
  "/sending-profiles": "Sending Profiles",
  "/landing-pages": "Landing Pages",
  "/phishing-emails": "Phishing Emails",
  "/phishing-websites": "Phishing Websites",
  "/training-modules": "Trainning Modules",
  "/account-settings": "Account Settings",
  "/logging-activity": "Logging Activity",
  "/environtment-check": "Environment Check",
  "/report-thanks": "Report Phishing",
  "/": "Login",
  "/login": "Login",
  "/unauthorized": "Not Found",
  "*": "Not Found",
};